### ISSUE TITLE
the end of pilgrims way sign in fungal wastes crashes my game when i interact with it

### ISSUE THREAD

**Issue by Flaming59** [Korzer420/LoreMaster#3] opened 2022-08-07 14:07 UTC
when i go to the fungal wastes and interact with the sign where the bridge is to go into city of tears it crashes my game. i tried this with just the lore master mod (and obvi kept item changer and sfcore on to make the mod work) on too to make sure it wasn't anything else messing with it and yeah it's just the mod. i don't know what causing it.

**Comment by Korzer420** [comment] 2022-08-08 07:20
Hello, sorry for the late response. This seems odd to me. I tested it with 1.1.3 and it worked. In 1.1.4 I didn't change anything on the power itself. Unfortunately I can't test myself right now (will take about 8 hours). In the mean time, may I ask you to share your ModLog.txt and the lower part of your Player.txt (lower part because I think in the upper part your steam name is displayed iirc). Both should be located in your AppData Folder of the game "C:\Users\User\AppData\LocalLow\Team Cherry" or something. Also I'd like to ask you to test if you the acquisition of the power is the problem or the activation of the power itself. To test that, you have to manually give yourself the power (on another savefile would be best). To do that, follow the following instructions:
- Create a options_1.txt file in the mod folder of loremaster (replace the 1 with the save slot which you wanna use to test).
- Add these two lines to the file:
```
%modify%
%GloryOfTheWealth% global | add
```
- Save and close this file.
- Start your save slot file.

This should grant you the ability. If it doesn't crash then, the acquisition is the problem.

**Comment by Korzer420** [comment] 2022-08-08 16:44
Ok the problem was caused by my stupidity. Fixed with 1.1.5

**Closed by Korzer420** 2022-08-08 16:44 UTC
